# Generated by Django 4.2.5 on 2023-12-03 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_compra', models.DateTimeField()),
                ('producto', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('grupo_producto', models.CharField(max_length=10, null=True)),
                ('cantidad_comprada', models.IntegerField()),
                ('sucursal', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_Detalle_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField()),
                ('nombre_producto', models.CharField(max_length=50)),
                ('grupo_producto', models.CharField(max_length=10)),
                ('cantidad_total_vendida', models.IntegerField()),
                ('total_recaudado_prod', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField()),
                ('total_compra', models.IntegerField()),
                ('cantidad_prod_grupo_a', models.IntegerField()),
                ('total_compra_grupo_a', models.IntegerField()),
                ('cantidad_prod_grupo_b', models.IntegerField()),
                ('total_compra_grupo_b', models.IntegerField()),
                ('cantidad_prod_grupo_c', models.IntegerField()),
                ('total_compra_grupo_c', models.IntegerField()),
                ('cantidad_prod_grupo_d', models.IntegerField()),
                ('total_compra_grupo_d', models.IntegerField()),
                ('cantidad_prod_sin_grupo', models.IntegerField()),
                ('total_compra_sin_grupo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('ubicacion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grupoproducto')),
            ],
        ),
    ]
