# Generated by Django 4.2.5 on 2023-09-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField()),
                ('compra', models.DateTimeField()),
                ('producto', models.CharField(max_length=50)),
                ('grupo_producto', models.CharField(max_length=10)),
                ('cantidad_comprada', models.IntegerField()),
                ('sucursal', models.CharField(max_length=40)),
            ],
        ),
    ]
